<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\EliteMud.Application\EliteMud.Application.csproj" />
    <ProjectReference Include="..\EliteMud.Game\EliteMud.Game.csproj" />
    <ProjectReference Include="..\EliteMud.Data\EliteMud.Data.csproj" />
    <ProjectReference Include="..\EliteMud.Legacy\EliteMud.Legacy.csproj" />
    <ProjectReference Include="..\EliteMud.Scripting\EliteMud.Scripting.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="EliteMud.Tests" />
  </ItemGroup>

</Project>
